import Foundation

/// Applies extra domains to /etc/hosts between UrgeLock markers (needs admin via osascript).
final class HostsBlocklist {
    static let shared = HostsBlocklist()

    private let beginMarker = "# BEGIN UrgeLock"
    private let endMarker = "# END UrgeLock"

    private init() {}

    private var blocklistFilenames: [String] {
        ["extra-domains.txt", "doh-endpoints.txt"]
    }

    /// Built-in adult extras + DoH/Secure-DNS endpoints (so browsers cannot bypass hosts).
    func loadBundledDomains() -> [String] {
        var set = Set<String>()
        for name in blocklistFilenames {
            for url in candidateURLs(for: name) {
                if let text = try? String(contentsOf: url, encoding: .utf8) {
                    for d in parseDomainList(text) { set.insert(d) }
                    break
                }
            }
        }
        return set.sorted()
    }

    private func candidateURLs(for filename: String) -> [URL] {
        var urls: [URL] = []
        if let res = Bundle.main.resourceURL?.appendingPathComponent("blocklists/\(filename)") {
            urls.append(res)
        }
        let dev = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("Resources/blocklists/\(filename)")
        urls.append(dev)
        return urls
    }

    func parseDomainList(_ text: String) -> [String] {
        text.split(separator: "\n").compactMap { line -> String? in
            let t = line.trimmingCharacters(in: .whitespaces)
            if t.isEmpty || t.hasPrefix("#") { return nil }
            return AllowlistStore.normalize(t)
        }
    }

    /// Bundled built-in list + user-added list (from the app UI).
    func allConfiguredDomains() -> [String] {
        var set = Set(loadBundledDomains())
        for d in UserBlocklistStore.shared.domains {
            set.insert(d)
        }
        return set.sorted()
    }

    /// Domains to sinkhole = (bundled + user extras) − allowlist (and www variants).
    func effectiveBlockDomains() -> [String] {
        let allow = Set(AllowlistStore.shared.domains)
        var set = Set<String>()
        for d in allConfiguredDomains() {
            let bare = d.hasPrefix("www.") ? String(d.dropFirst(4)) : d
            if allow.contains(d) || allow.contains(bare) { continue }
            set.insert(bare)
            set.insert("www." + bare)
        }
        return set.sorted()
    }

    func hostsBlockSection() -> String {
        var lines = [beginMarker, "# Managed by UrgeLock — do not edit by hand"]
        for d in effectiveBlockDomains() {
            lines.append("0.0.0.0 \(d)")
        }
        lines.append(endMarker)
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Admin helpers

    /// Run a Python file as root via osascript admin dialog.
    private func runPythonHelperAsAdmin(at helperURL: URL) -> String? {
        // quoted form of path for AppleScript
        let path = helperURL.path
        let script = """
        try
            do shell script "python3 " & quoted form of "\(path)" with administrator privileges
            return "ok"
        on error errMsg number errNum
            return "error:" & errMsg
        end try
        """
        let r = Shell.run("/usr/bin/osascript", arguments: ["-e", script])
        let out = (r.stdout + r.stderr).trimmingCharacters(in: .whitespacesAndNewlines)
        if r.exitCode != 0 || out.hasPrefix("error:") {
            return out.isEmpty ? "Admin hosts update failed" : out
        }
        _ = Shell.run("/usr/bin/dscacheutil", arguments: ["-flushcache"])
        _ = Shell.run("/usr/bin/killall", arguments: ["-HUP", "mDNSResponder"])
        return nil
    }

    /// Apply hosts section with admin privileges (GUI password prompt).
    func applyWithAdmin() -> String? {
        let section = hostsBlockSection()
        let sectionURL = AppConfig.supportDirectory.appendingPathComponent("hosts-section.txt")
        let helperURL = AppConfig.supportDirectory.appendingPathComponent("apply-hosts.py")

        do {
            try section.write(to: sectionURL, atomically: true, encoding: .utf8)
        } catch {
            return "Failed to write temp hosts section: \(error.localizedDescription)"
        }

        // Paths baked into the helper so we never depend on AppleScript variable interpolation.
        let sectionPathLiteral = sectionURL.path
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")

        let py = """
        #!/usr/bin/env python3
        # Generated by UrgeLock — applies managed hosts block section.
        from pathlib import Path

        section_path = Path(\"\(sectionPathLiteral)\")
        hosts_path = Path("/etc/hosts")
        begin = "# BEGIN UrgeLock"
        end = "# END UrgeLock"

        text = hosts_path.read_text(encoding="utf-8", errors="replace")
        while begin in text and end in text:
            i = text.index(begin)
            j = text.index(end, i) + len(end)
            if j < len(text) and text[j] == "\\n":
                j += 1
            text = text[:i] + text[j:]

        section = section_path.read_text(encoding="utf-8", errors="replace")
        if not text.endswith("\\n"):
            text += "\\n"
        text = text + section
        hosts_path.write_text(text, encoding="utf-8")
        print("ok")
        """

        do {
            try py.write(to: helperURL, atomically: true, encoding: .utf8)
        } catch {
            return "Failed to write hosts helper: \(error.localizedDescription)"
        }

        return runPythonHelperAsAdmin(at: helperURL)
    }

    func removeWithAdmin() -> String? {
        let helperURL = AppConfig.supportDirectory.appendingPathComponent("remove-hosts.py")
        let py = """
        #!/usr/bin/env python3
        # Generated by UrgeLock — removes managed hosts block section.
        from pathlib import Path

        hosts_path = Path("/etc/hosts")
        begin = "# BEGIN UrgeLock"
        end = "# END UrgeLock"

        text = hosts_path.read_text(encoding="utf-8", errors="replace")
        while begin in text and end in text:
            i = text.index(begin)
            j = text.index(end, i) + len(end)
            if j < len(text) and text[j] == "\\n":
                j += 1
            text = text[:i] + text[j:]
        hosts_path.write_text(text, encoding="utf-8")
        print("ok")
        """

        do {
            try py.write(to: helperURL, atomically: true, encoding: .utf8)
        } catch {
            return "Failed to write hosts helper: \(error.localizedDescription)"
        }

        return runPythonHelperAsAdmin(at: helperURL)
    }
}
